### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by nevaways** [cynthia/ocp-osx#1]
Is there a single comprehensive list of all the commands from ocp?

**Comment by cynthia** [comment]
No, not really. There is this: http://www.cubic.org/player/doc/node42.htm
and a lot of things scattered around in the same documentation. Some of the alt shortcuts may not work, as it will be considered text input.

**Comment by mywave82** [comment]
Press ALT-K inside the player at any given place you wonder which key commands are available

**Comment by cynthia** [comment]
Thanks a lot for the tip!
